openapi: 3.0.3
info:
  title: Despacha ai API
  version: 1.0.0
  description: Your project description
paths:
  /api/auth/login/:
    post:
      operationId: auth_login_create
      tags:
      - auth
      security:
      - knoxApiToken: []
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/logout/:
    post:
      operationId: auth_logout_create
      tags:
      - auth
      security:
      - knoxApiToken: []
      responses:
        '200':
          description: No response body
  /api/auth/logoutall/:
    post:
      operationId: auth_logoutall_create
      description: |-
        Log the user out of all sessions
        I.E. deletes all auth tokens for the user
      tags:
      - auth
      security:
      - knoxApiToken: []
      responses:
        '200':
          description: No response body
  /api/auth/register/:
    post:
      operationId: auth_register_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/pagamento:
    get:
      operationId: pagamento_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: month
        schema:
          type: number
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: year
        schema:
          type: number
      tags:
      - pagamento
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedPagamentoReaderList'
          description: ''
  /api/pagamento/{pagamento_id}/pagar:
    post:
      operationId: pagamento_pagar_create
      parameters:
      - in: path
        name: pagamento_id
        schema:
          type: integer
        required: true
      tags:
      - pagamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pagar'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pagar'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Pagar'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pagar'
          description: ''
  /api/pagamento/contrato:
    post:
      operationId: pagamento_contrato_create
      tags:
      - pagamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PagamentoContrato'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PagamentoContrato'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PagamentoContrato'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagamentoContrato'
          description: ''
  /api/pagamento/implantacao:
    post:
      operationId: pagamento_implantacao_create
      tags:
      - pagamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PagamentoImplantacao'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PagamentoImplantacao'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PagamentoImplantacao'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagamentoImplantacao'
          description: ''
  /api/pagamento/processo:
    get:
      operationId: pagamento_processo_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - pagamento
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProcessoDetailList'
          description: ''
    post:
      operationId: pagamento_processo_create
      tags:
      - pagamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Processo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Processo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Processo'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Processo'
          description: ''
  /api/pagamento/processo/{processo_id}:
    get:
      operationId: pagamento_processo_retrieve
      parameters:
      - in: path
        name: processo_id
        schema:
          type: integer
        required: true
      tags:
      - pagamento
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessoDetail'
          description: ''
  /api/pagamento/processo/{processo_id}/pendentes:
    get:
      operationId: pagamento_processo_pendentes_retrieve
      parameters:
      - in: path
        name: processo_id
        schema:
          type: integer
        required: true
      tags:
      - pagamento
      security:
      - knoxApiToken: []
      responses:
        '200':
          description: No response body
  /api/pessoas/advogado:
    get:
      operationId: pessoas_advogado_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - pessoas
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedAdvogadoList'
          description: ''
    post:
      operationId: pessoas_advogado_create
      tags:
      - pessoas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Advogado'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Advogado'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Advogado'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Advogado'
          description: ''
  /api/pessoas/cliente:
    get:
      operationId: pessoas_cliente_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - pessoas
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedClienteList'
          description: ''
  /api/pessoas/corretor:
    get:
      operationId: pessoas_corretor_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - pessoas
      security:
      - knoxApiToken: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCorretorList'
          description: ''
    post:
      operationId: pessoas_corretor_create
      tags:
      - pessoas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Corretor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Corretor'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Corretor'
        required: true
      security:
      - knoxApiToken: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Corretor'
          description: ''
components:
  schemas:
    Advogado:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 100
        oab_numero:
          type: string
          nullable: true
          maxLength: 20
        email:
          type: string
          format: email
          nullable: true
          maxLength: 254
        telefone:
          type: string
          nullable: true
          maxLength: 15
        comissao_padrao:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,2})?$
        chave_pix:
          type: string
          nullable: true
          maxLength: 255
      required:
      - id
      - nome
    Cliente:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 255
        cpf:
          type: string
          nullable: true
          maxLength: 14
        criado_em:
          type: string
          format: date-time
          readOnly: true
      required:
      - criado_em
      - id
      - nome
    Corretor:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 255
        email:
          type: string
          format: email
          maxLength: 254
        advogado:
          type: integer
        comissao_padrao:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,2})?$
        chave_pix:
          type: string
          nullable: true
          maxLength: 255
      required:
      - advogado
      - email
      - id
      - nome
    PagamentoContrato:
      type: object
      properties:
        processo:
          type: integer
          writeOnly: true
        valor_total:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          writeOnly: true
        entrada:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        valor_parcela:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        numero_parcelas:
          type: integer
          maximum: 2147483647
          minimum: 0
        vencimento_entrada:
          type: string
          format: date
        vencimento_parcela:
          type: string
          format: date
          writeOnly: true
          description: Data de vencimento da primeira parcela.
      required:
      - entrada
      - numero_parcelas
      - processo
      - valor_parcela
      - valor_total
      - vencimento_entrada
      - vencimento_parcela
    PagamentoImplantacao:
      type: object
      properties:
        processo:
          type: integer
          writeOnly: true
        valor_total:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        porcentagem_escritorio:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,2})?$
        data_vencimento:
          type: string
          format: date
        local_pagamento:
          type: string
          maxLength: 255
      required:
      - data_vencimento
      - porcentagem_escritorio
      - processo
    PagamentoReader:
      type: object
      properties:
        tipo:
          $ref: '#/components/schemas/TipoEnum'
        criado_em:
          type: string
          format: date-time
          readOnly: true
        processo:
          type: string
          readOnly: true
      required:
      - criado_em
      - processo
      - tipo
    Pagar:
      type: object
      properties:
        valor_pago:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        data_pagamento:
          type: string
          format: date
        quitar:
          type: boolean
          default: false
      required:
      - data_pagamento
      - valor_pago
    PaginatedAdvogadoList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Advogado'
    PaginatedClienteList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Cliente'
    PaginatedCorretorList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Corretor'
    PaginatedPagamentoReaderList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/PagamentoReader'
    PaginatedProcessoDetailList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/ProcessoDetail'
    Processo:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        cliente:
          type: string
          writeOnly: true
        cpf:
          type: string
          writeOnly: true
        advogado:
          type: integer
        corretor:
          type: integer
          nullable: true
        criado_em:
          type: string
          format: date-time
        observacao:
          type: string
          nullable: true
      required:
      - advogado
      - id
    ProcessoDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        cliente:
          type: integer
          nullable: true
        criado_em:
          type: string
          format: date-time
        pagamentos:
          type: string
          readOnly: true
      required:
      - id
      - pagamentos
    TipoEnum:
      enum:
      - IMPLANTACAO
      - CONTRATO_PARCELA
      - CONTRATO_ENTRADA
      type: string
      description: |-
        * `IMPLANTACAO` - Implantacao
        * `CONTRATO_PARCELA` - Parcela
        * `CONTRATO_ENTRADA` - Entrada
    User:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
          maxLength: 128
        is_staff:
          type: boolean
          writeOnly: true
          title: Staff status
          description: Designates whether the user can log into this admin site.
        is_superuser:
          type: boolean
          writeOnly: true
          title: Superuser status
          description: Designates that this user has all permissions without explicitly
            assigning them.
      required:
      - password
      - username
  securitySchemes:
    knoxApiToken:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
