openapi: 3.0.3
info:
  title: Despacha ai API
  version: 1.0.0
  description: Your project description
paths:
  /api/auth/login/:
    post:
      operationId: login_create
      tags:
      - login
      security:
      - knoxApiToken: []
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/logout/:
    post:
      operationId: logout_create
      tags:
      - logout
      security:
      - knoxApiToken: []
      responses:
        '200':
          description: No response body
  /api/auth/logoutall/:
    post:
      operationId: logoutall_create
      description: |-
        Log the user out of all sessions
        I.E. deletes all auth tokens for the user
      tags:
      - logoutall
      security:
      - knoxApiToken: []
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    knoxApiToken:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
