sonar.projectKey=JuninhoCarlos_dispachai-api
sonar.organization=juninhocarlos

sonar.sources=pagamento,pessoa,identity,api
sonar.tests=pagamento/tests,pessoa/tests,identity/tests
sonar.language=py

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/migrations/**,manage.py,api/wsgi.py,api/asgi.py,api/settings.py

sonar.exclusions=**/migrations/**,manage.py
