# Generated by Django 5.2.8 on 2025-12-06 19:05

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advogado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "oab_numero",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "comissao_padrao",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal(
                                    "0.01000000000000000020816681711721685132943093776702880859375"
                                )
                            ),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Corretor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "comissao_padrao",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal(
                                    "0.01000000000000000020816681711721685132943093776702880859375"
                                )
                            ),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "advogado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corretores",
                        to="pessoa.advogado",
                    ),
                ),
            ],
        ),
    ]
