# Generated by Django 5.2.8 on 2026-02-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="corretor",
            name="chave_pix",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
