# Generated by Django 5.2.8 on 2026-03-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoa", "0003_advogado_chave_pix"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cpf", models.CharField(blank=True, max_length=14, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
