# Generated by Django 5.2.8 on 2026-03-21 15:30

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoa", "0004_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advogado",
            name="comissao_padrao",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal(
                            "0.01000000000000000020816681711721685132943093776702880859375"
                        )
                    ),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="corretor",
            name="comissao_padrao",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal(
                            "0.01000000000000000020816681711721685132943093776702880859375"
                        )
                    ),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
    ]
