# Generated by Django 5.2.8 on 2026-06-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoa", "0005_alter_advogado_comissao_padrao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corretor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
