# Generated by Django 5.2.8 on 2025-11-18 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despacho", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="processo",
            old_name="data_criacao",
            new_name="criado_em",
        ),
        migrations.AddField(
            model_name="advogado",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="corretor",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
