# Generated by Django 5.2.8 on 2025-11-18 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despacho", "0002_rename_data_criacao_processo_criado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advogado",
            name="comissao_padrao",
            field=models.DecimalField(
                decimal_places=2,
                default=30.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
