# Generated by Django 5.2.8 on 2025-11-18 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despacho", "0003_alter_advogado_comissao_padrao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corretor",
            name="comissao_padrao",
            field=models.DecimalField(
                decimal_places=2,
                default=30.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="comissao_ajustada_advogado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="comissao_ajustada_corretor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
