# Generated by Django 5.2.8 on 2025-12-05 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despacho", "0004_alter_corretor_comissao_padrao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("IMPLANTACAO", "Implantacao"),
                            ("CONTRATO", "Contrato"),
                            ("RPV", "Rpv"),
                            ("AUXILIODOENCA", "Auxiliodoenca"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="processo",
            name="valor_total",
        ),
        migrations.CreateModel(
            name="PagamentoAuxilioDoenca",
            fields=[
                (
                    "pagamento_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="despacho.pagamento",
                    ),
                ),
                ("valor_mensal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Pagamento Auxílio Doença",
            },
            bases=("despacho.pagamento",),
        ),
        migrations.CreateModel(
            name="PagamentoContrato",
            fields=[
                (
                    "pagamento_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="despacho.pagamento",
                    ),
                ),
                ("entrada", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valor_parcela", models.DecimalField(decimal_places=2, max_digits=10)),
                ("meses", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Pagamento de Contrato",
            },
            bases=("despacho.pagamento",),
        ),
        migrations.CreateModel(
            name="PagamentoImplantacao",
            fields=[
                (
                    "pagamento_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="despacho.pagamento",
                    ),
                ),
                (
                    "porcentagem_escritorio",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Pagamento de Implantação",
            },
            bases=("despacho.pagamento",),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagamentos",
                to="despacho.processo",
            ),
        ),
    ]
