# Generated by Django 5.2.8 on 2025-12-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("despacho", "0005_pagamento_remove_processo_valor_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagamento",
            name="processo",
        ),
        migrations.RemoveField(
            model_name="pagamentocontrato",
            name="pagamento_ptr",
        ),
        migrations.RemoveField(
            model_name="pagamentoauxiliodoenca",
            name="pagamento_ptr",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="advogado",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="corretor",
        ),
        migrations.DeleteModel(
            name="PagamentoImplantacao",
        ),
        migrations.DeleteModel(
            name="PagamentoContrato",
        ),
        migrations.DeleteModel(
            name="Pagamento",
        ),
        migrations.DeleteModel(
            name="PagamentoAuxilioDoenca",
        ),
        migrations.DeleteModel(
            name="Processo",
        ),
    ]
