# Generated by Django 5.2.8 on 2025-12-05 23:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("despacho", "0006_remove_pagamento_processo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("IMPLANTACAO", "Implantacao"),
                            ("CONTRATO", "Contrato"),
                            ("RPV", "Rpv"),
                            ("AUXILIODOENCA", "Auxiliodoenca"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PagamentoAuxilioDoenca",
            fields=[
                (
                    "pagamento_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pagamento.pagamento",
                    ),
                ),
                ("valor_mensal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Pagamento Auxílio Doença",
            },
            bases=("pagamento.pagamento",),
        ),
        migrations.CreateModel(
            name="PagamentoContrato",
            fields=[
                (
                    "pagamento_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pagamento.pagamento",
                    ),
                ),
                ("entrada", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valor_parcela", models.DecimalField(decimal_places=2, max_digits=10)),
                ("meses", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Pagamento de Contrato",
            },
            bases=("pagamento.pagamento",),
        ),
        migrations.CreateModel(
            name="PagamentoImplantacao",
            fields=[
                (
                    "pagamento_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pagamento.pagamento",
                    ),
                ),
                (
                    "porcentagem_escritorio",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Pagamento de Implantação",
            },
            bases=("pagamento.pagamento",),
        ),
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_processo", models.TextField(blank=True, null=True)),
                (
                    "comissao_ajustada_advogado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal(
                                    "0.01000000000000000020816681711721685132943093776702880859375"
                                )
                            ),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "comissao_ajustada_corretor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal(
                                    "0.01000000000000000020816681711721685132943093776702880859375"
                                )
                            ),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "advogado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processos",
                        to="despacho.advogado",
                    ),
                ),
                (
                    "corretor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processos",
                        to="despacho.corretor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pagamento",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagamentos",
                to="pagamento.processo",
            ),
        ),
    ]
