# Generated by Django 5.2.8 on 2025-12-07 13:18

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pessoa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("IMPLANTACAO", "Implantacao"),
                            ("CONTRATO", "Contrato"),
                            ("RPV", "Rpv"),
                            ("AUXILIODOENCA", "Auxiliodoenca"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PagamentoContrato",
            fields=[
                (
                    "pagamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="contrato",
                        serialize=False,
                        to="pagamento.pagamento",
                    ),
                ),
                ("entrada", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valor_parcela", models.DecimalField(decimal_places=2, max_digits=10)),
                ("numero_parcelas", models.PositiveIntegerField()),
                ("vencimento_entrada", models.DateField()),
                (
                    "status_entrada",
                    models.CharField(
                        choices=[
                            ("PLANEJADO", "Planejado"),
                            ("PAGO", "Pago"),
                            ("PARCIALMENTE_PAGO", "Parcialmente Pago"),
                            ("ATRASADO", "Atrasado"),
                        ],
                        default="PLANEJADO",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento de Contrato",
            },
        ),
        migrations.CreateModel(
            name="PagamentoImplantacao",
            fields=[
                (
                    "pagamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="implantacao",
                        serialize=False,
                        to="pagamento.pagamento",
                    ),
                ),
                (
                    "porcentagem_escritorio",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("data_vencimento", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANEJADO", "Planejado"),
                            ("PAGO", "Pago"),
                            ("PARCIALMENTE_PAGO", "Parcialmente Pago"),
                            ("ATRASADO", "Atrasado"),
                        ],
                        default="PLANEJADO",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento de Implantação",
            },
        ),
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.TextField(blank=True, null=True)),
                (
                    "comissao_ajustada_advogado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal(
                                    "0.01000000000000000020816681711721685132943093776702880859375"
                                )
                            ),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "comissao_ajustada_corretor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal(
                                    "0.01000000000000000020816681711721685132943093776702880859375"
                                )
                            ),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "advogado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processos",
                        to="pessoa.advogado",
                    ),
                ),
                (
                    "corretor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processos",
                        to="pessoa.corretor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pagamento",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pagamentos",
                to="pagamento.processo",
            ),
        ),
        migrations.CreateModel(
            name="PagamentoParcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_parcela", models.DecimalField(decimal_places=2, max_digits=10)),
                ("numero_parcela", models.PositiveIntegerField()),
                ("data_vencimento", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANEJADO", "Planejado"),
                            ("PAGO", "Pago"),
                            ("PARCIALMENTE_PAGO", "Parcialmente Pago"),
                            ("ATRASADO", "Atrasado"),
                        ],
                        default="PLANEJADO",
                        max_length=20,
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas",
                        to="pagamento.pagamentocontrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento de Parcelas",
            },
        ),
    ]
