# Generated by Django 5.2.8 on 2025-12-06 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="processo",
            old_name="nome_processo",
            new_name="cliente",
        ),
    ]
