# Generated by Django 5.2.8 on 2025-12-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamento",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagamentos",
                to="pagamento.processo",
            ),
        ),
    ]
