# Generated by Django 5.2.8 on 2025-12-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0002_alter_pagamento_processo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamentocontrato",
            name="vencimento_parcela",
            field=models.DateField(blank=True, null=True),
        ),
    ]
