# Generated by Django 5.2.8 on 2025-12-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0002_rename_nome_processo_processo_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamentoimplantacao",
            name="data_pagamento",
            field=models.DateField(default="2025-02-10"),
            preserve_default=False,
        ),
    ]
