# Generated by Django 5.2.8 on 2025-12-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0003_pagamentoimplantacao_data_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamentocontrato",
            name="data_inicio_pagamento",
            field=models.DateField(default="2025-12-29"),
            preserve_default=False,
        ),
    ]
