# Generated by Django 5.2.8 on 2025-12-13 12:57

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0004_alter_processo_criado_em"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processo",
            name="criado_em",
            field=models.DateTimeField(
                default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
