# Generated by Django 5.2.8 on 2025-12-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0004_pagamentocontrato_data_inicio_pagamento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagamentocontrato",
            old_name="data_inicio_pagamento",
            new_name="vencimento_entrada",
        ),
        migrations.RenameField(
            model_name="pagamentoimplantacao",
            old_name="data_pagamento",
            new_name="data_vencimento",
        ),
        migrations.AddField(
            model_name="pagamentocontrato",
            name="status_entrada",
            field=models.CharField(
                choices=[
                    ("PLANEJADO", "Planejado"),
                    ("PAGO", "Pago"),
                    ("PARCIALMENTE_PAGO", "Parcialmente Pago"),
                    ("ATRASADO", "Atrasado"),
                ],
                default="PLANEJADO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pagamentoimplantacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANEJADO", "Planejado"),
                    ("PAGO", "Pago"),
                    ("PARCIALMENTE_PAGO", "Parcialmente Pago"),
                    ("ATRASADO", "Atrasado"),
                ],
                default="PLANEJADO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pagamentos",
                to="pagamento.processo",
            ),
        ),
        migrations.DeleteModel(
            name="PagamentoAuxilioDoenca",
        ),
    ]
