# Generated by Django 5.2.8 on 2025-12-13 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0005_alter_processo_criado_em"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processo",
            name="criado_em",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
