# Generated by Django 5.2.8 on 2025-12-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "pagamento",
            "0005_rename_data_inicio_pagamento_pagamentocontrato_vencimento_entrada_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagamentocontrato",
            old_name="meses",
            new_name="numero_parcelas",
        ),
    ]
