# Generated by Django 5.2.8 on 2025-12-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0006_alter_processo_criado_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="observacao",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
