# Generated by Django 5.2.8 on 2026-01-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0007_processo_observacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagamentoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pagamento", models.IntegerField()),
                (
                    "valor_recebido",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("data_pagamento", models.DateField()),
                ("data_cadastro_pagamento", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("IMPLANTACAO", "Implantacao"),
                            ("CONTRATO", "Contrato"),
                            ("CONTRATO_PARCELA", "Parcela"),
                            ("CONTRATO_ENTRADA", "Entrada"),
                            ("RPV", "Rpv"),
                            ("AUXILIODOENCA", "Auxiliodoenca"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("IMPLANTACAO", "Implantacao"),
                    ("CONTRATO", "Contrato"),
                    ("CONTRATO_PARCELA", "Parcela"),
                    ("CONTRATO_ENTRADA", "Entrada"),
                    ("RPV", "Rpv"),
                    ("AUXILIODOENCA", "Auxiliodoenca"),
                ],
                max_length=20,
            ),
        ),
    ]
