# Generated by Django 5.2.8 on 2026-02-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0008_pagamentoevento_alter_pagamento_tipo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagamentoevento",
            old_name="data_cadastro_pagamento",
            new_name="criado_em",
        ),
        migrations.RemoveField(
            model_name="pagamento",
            name="valor_total",
        ),
        migrations.RemoveField(
            model_name="pagamentoparcela",
            name="valor_pago",
        ),
        migrations.AddField(
            model_name="pagamentoimplantacao",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name="pagamentoparcela",
            name="pagamento",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcela",
                to="pagamento.pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="pagamentoevento",
            name="pagamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidacoes",
                to="pagamento.pagamento",
            ),
        ),
    ]
