# Generated by Django 5.2.8 on 2026-02-01 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pagamento",
            "0009_rename_data_cadastro_pagamento_pagamentoevento_criado_em_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagamentoparcela",
            name="id",
        ),
        migrations.AlterField(
            model_name="pagamentoparcela",
            name="pagamento",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="parcela",
                serialize=False,
                to="pagamento.pagamento",
            ),
        ),
    ]
