# Generated by Django 5.2.8 on 2026-02-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0010_remove_pagamentoparcela_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagamentocontrato",
            name="pagamento",
        ),
        migrations.RemoveField(
            model_name="pagamentoevento",
            name="tipo",
        ),
        migrations.AddField(
            model_name="pagamentocontrato",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
