# Generated by Django 5.2.8 on 2026-02-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0011_remove_pagamentocontrato_pagamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamentoparcela",
            name="tipo",
            field=models.CharField(
                choices=[("ENTRADA", "Entrada"), ("PARCELA", "Parcela")],
                default="PARCELA",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pagamentoparcela",
            name="numero_parcela",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
