# Generated by Django 5.2.8 on 2026-02-01 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0012_pagamentoparcela_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamentoparcela",
            name="pagamento",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="parcelas_contrato",
                serialize=False,
                to="pagamento.pagamento",
            ),
        ),
    ]
