# Generated by Django 5.2.8 on 2026-02-07 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0013_alter_pagamentoparcela_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("IMPLANTACAO", "Implantacao"),
                    ("CONTRATO_PARCELA", "Parcela"),
                    ("CONTRATO_ENTRADA", "Entrada"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pagamentoparcela",
            name="pagamento",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="parcela",
                serialize=False,
                to="pagamento.pagamento",
            ),
        ),
    ]
