# Generated by Django 5.2.8 on 2026-03-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0014_alter_pagamento_tipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamentoimplantacao",
            name="local_pagamento",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
