# Generated by Django 5.2.8 on 2026-03-14 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0016_cliente_alter_processo_cliente"),
        ("pessoa", "0004_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processo",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processos",
                to="pessoa.cliente",
            ),
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
    ]
