# Generated by Django 5.2.8 on 2026-04-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0017_alter_processo_cliente_delete_cliente"),
        ("pessoa", "0005_alter_advogado_comissao_padrao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ADVOGADO", "Advogado"), ("CORRETOR", "Corretor")],
                        max_length=20,
                    ),
                ),
                (
                    "valor_repassado",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "comissao_porcentagem",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("data_repasse", models.DateField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "advogado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pessoa.advogado",
                    ),
                ),
                (
                    "corretor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pessoa.corretor",
                    ),
                ),
                (
                    "eventos",
                    models.ManyToManyField(
                        related_name="repasses", to="pagamento.pagamentoevento"
                    ),
                ),
                (
                    "pagamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repasses",
                        to="pagamento.pagamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repasse",
            },
        ),
    ]
