# Generated by Django 5.2.8 on 2026-06-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0018_repasse"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagamentoimplantacao",
            old_name="valor_total",
            new_name="valor_beneficio",
        ),
    ]
